domain: suisen-cp.github.io
baseurl: /apps/
url: https://suisen-cp.github.io

theme: minima
plugins:
  - jekyll-feed

apps:
  graph-editor:
    title: Graph Editor
    description: GUI tool for editing network graphs
    url: graph-editor