domain: suisen-cp.github.io
baseurl: /
url: https://suisen-cp.github.io

theme: minima
plugins:
  - jekyll-feed

graph-editor:
  title: Graph Editor
  description: GUI tool for editing network graphs
  url: graph-editor